Task 1:   

Write a Python program to reverse an array without using an in-built function. 

In [ ]:
import numpy as np
arr = np.array([])
arr2 = np.array([])
n=int(input('ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: '))
print("ENTER THE ELEMENTS OF THE ARRAY: ")
for i in range(1,n+1):
  num=int(input(""))
  arr=np.append(arr,num)
print('ORIGINAL ARRAY IS:',arr)
for i in range (n-1,-1,-1):
  arr2=np.append(arr2,arr[i])
print('REVERSED ARRAY IS',arr2)

ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: 3
ENTER THE ELEMENTS OF THE ARRAY: 
1
2
3
ORIGINAL ARRAY IS: [1. 2. 3.]
REVERSED ARRAY IS [3. 2. 1.]


 

Task 2:   

Write a Python program to find the frequency of a user-given number in an array.(without using an in-built function) 

 

In [ ]:
import numpy as np
arr = np.array([])
n=int(input('ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: '))
print("ENTER THE ELEMENTS OF THE ARRAY: ")
for i in range(1,n+1):
  num=int(input(""))
  arr=np.append(arr,num)
print('ORIGINAL ARRAY IS:',arr)
k=int(input("ENTER THE ELEMENT WHOSE FREQUENCY NEEDS TO BE FOUND: "))
count=0
for j in arr:
  if k == j:
    count+=1
print("THE FREQUENCY IS {}".format(count))

ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: 5
ENTER THE ELEMENTS OF THE ARRAY: 
1
3
3
1
3
ORIGINAL ARRAY IS: [1. 3. 3. 1. 3.]
ENTER THE ELEMENT WHOSE FREQUENCY NEEDS TO BE FOUND: 3
THE FREQUENCY IS 3


Task 3:  

Write a Python program to place all negative numbers in the array at the end of the array and positive numbers at the beginning. (without using an in-built function) 

In [ ]:
import numpy as np
arr = np.array([])
arr2 = np.array([])
arr3=np.array([])
n=int(input('ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: '))
print("ENTER THE ELEMENTS OF THE ARRAY: ")
for i in range(1,n+1):
  num=int(input(""))
  arr=np.append(arr,num)
print('ORIGINAL ARRAY IS:',arr)
for j in arr:
  if j >=0:
    arr2=np.append(arr2,j)
  else:
    arr3=np.append(arr3,j)
arr2=np.append(arr2,arr3)
print("SORTED ARRAY {}".format(arr2))

ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: 5
ENTER THE ELEMENTS OF THE ARRAY: 
-2
3
-1
5
3
ORIGINAL ARRAY IS: [-2.  3. -1.  5.  3.]
SORTED ARRAY [ 3.  5.  3. -2. -1.]


Task 4:   

Write a Python program to sort an array in the waveform.(use the inbuilt function to sort an array) 

Example :  

Input: A[ ] = {2, 4, 6, 8, 10, 20} 

Output: A[ ]  = {4, 2, 8, 6, 20, 10} 

In [ ]:
import numpy as np
arr = np.array([])
n=int(input('ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: '))
print("ENTER THE ELEMENTS OF THE ARRAY: ")
for i in range(1,n+1):
  num=int(input(""))
  arr=np.append(arr,num)
print('ORIGINAL ARRAY IS:',arr)
arr=np.sort(arr)
j = 0
while j < n:
    t = arr[j]
    arr[j] = arr[j + 1]
    arr[j+1] = t
    j+=2
print(arr)

ENTER THE NUMBER OF ELEMENTS IN THE ARRAY: 6
ENTER THE ELEMENTS OF THE ARRAY: 
2
4
6
8
10
20
ORIGINAL ARRAY IS: [ 2.  4.  6.  8. 10. 20.]
[ 4.  2.  8.  6. 20. 10.]


Task 5 :  

Write a Python program to print a given matrix in spiral form. 

Example :  

A = [[1 2 3] 

     [4 5 6] 

     [7 8 9]] 

Spiral form : 1 2 3 6 9 8 7 4 5 

In [ ]:
import numpy as np
mat = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
top = left = 0
bottom = len(mat) - 1
right = len(mat[0]) - 1
print('SPIRAL FORM: ',end='')
while True:
  if left > right:
    break
  for i in range(left, right + 1):
    print(mat[top][i], end=' ')
  top = top + 1
  if top > bottom:
    break
 
  for i in range(top, bottom + 1):
    print(mat[i][right], end=' ')
  right = right - 1
  if left > right:
    break
  for i in range(right, left - 1, -1):
    print(mat[bottom][i], end=' ')
  bottom = bottom - 1
  if top > bottom:
    break
  for i in range(bottom, top - 1, -1):
    print(mat[i][left], end=' ')
  left = left + 1




SPIRAL FORM: 1 2 3 6 9 8 7 4 5 

Task 6 :  

6.1 	Write a Python program to print ‘k’ smallest element in an unsorted array. 

6.2 	Write a Python program to print ‘k’ largest element in an unsorted array. 

In [ ]:
import numpy as np
arr=np.array([1,5,-9,0,11,-2,-19,19,7,4])
smallest=arr[0]
largest=arr[0]
for i in arr:
  if i < smallest:
    smallest= i
  if i > largest:
    largest=i
print("SMALLEST:",smallest)
print("LARGEST:",largest)

SMALLEST: -19
LARGEST: 19


Task 7: 

Write a Python Program to add two 3x3 Matrices using Nested Loop. 

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = np.array([])
for i in range(3):
  for j in range(3):
    sum=np.append(sum,arr[i,j]+arr2[i,j])
print("SUM:- ") 
print(sum.reshape(3,3))

SUM:- 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


Task 8: 

Write a Python Program to multiply two Matrices using Nested Loop. 

In [ ]:
arr = np.array([[1,2],[3,4]])
arr2 = np.array([[3,4],[5,6]]) 
product = np.zeros((2,2),int)
for i in range(2):
  for j in range(2):
    for k in range(2):
      product[i,j] += arr[i,k]*arr2[k,j]
print("PRODUCT:- ")
print(product)


PRODUCT:- 
[[13 16]
 [29 36]]


Task 9: 

Write a Python Program to Calculate the sum of all columns in a 2D NumPy array. (without using an in-built function) 

Example :   

A = [ [1 2 3] 

 	[1 1 1] 

 	[1 1 1]] 

 

Column wise Sum: 3 4 5 

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = 0
print("Column wise Sum: ")
for i in range(3):
  for j in range(3):
    sum += arr[j][i]
  print(sum)
  sum=0



Column wise Sum: 
12
15
18


 

Task 10: 

Write a Python Program to find Range and Coefficient of range of Array. 

Range = Max – Min 

Coefficient of Range = (Max – Min) / (Max + Min) 

Example :  

A = [10, 20, 30, 5, 8] 

Range : 25 

Coefficient of Range : 0.7142857142857143  


In [ ]:
arr = np.array([10,20,30,5,8])
range = np.max(arr)-np.min(arr)  
print("Range:",range)
denom = np.max(arr)+np.min(arr)
cor = range/denom
print("Coefficient of Range:",cor)


Range: 25
Coefficient of Range: 0.7142857142857143
